# Generated by Django 3.0.5 on 2020-04-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='language',
            new_name='source',
        ),
    ]
