# Generated by Django 3.0.5 on 2020-04-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20200428_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Links',
        ),
    ]
