# Generated by Django 3.0.5 on 2020-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_auto_20200428_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='source',
            field=models.CharField(default='yonsei.ac.kr', max_length=100),
        ),
    ]
